[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pypsa-to-gems-converter"
version = "0.0.1"
description = "Convert PyPSA networks into GEMS study folders for modelling and simulation."
readme = "README.md"
license = "MPL-2.0"
license-files = ["LICENSE", "AUTHORS.txt"]
authors = [
    { name = "Dusan Paripovic @dusanparipovic" },
    { name = "Nikola Ilic @nikolaredstork" },
    { name = "Thomas Bittar @tbittar" },
    { name = "Antoine Oustry @aoustry"}
]
requires-python = ">=3.11"
dependencies = [
    "pandas==2.2.3",
    "polars>=0.20.0",
    "pyarrow",
    "pypsa==1.2.0",
    "pyyaml==6.0.2",
    "pydantic==2.12.5",
    "gemspy==0.1.2",
]
classifiers = [
    # Classifiers here: https://pypi.org/classifiers/
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Repository = "https://github.com/AntaresSimulatorTeam/PyPSA-to-GEMS-Converter"
"Bug Tracker" = "https://github.com/AntaresSimulatorTeam/PyPSA-to-GEMS-Converter/issues"

[project.scripts]
pypsa-to-gems = "src.cli:main"

[dependency-groups]
dev = [
    "pytest==7.0.1",
    "pytest-xdist==3.8.0",
    "highspy>=1.5.0",
    "ruff~=0.9.6",
    "mypy~=1.15.0",
    "pre-commit~=4.1.0",
    "pandas-stubs>=2.0.0",
    "types-PyYAML>=6.0.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src", "src.*"]

[tool.setuptools.exclude-package-data]
"*" = ["*.ipynb"]

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [".git", ".venv", "venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "resources", "build", "dist"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"*.ipynb" = ["E402"]
"src/pypsa_preprocessor.py" = ["E712"]

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.mypy]
files = "src"
strict = true
plugins = ["pydantic.mypy"]
disable_error_code = ["attr-defined"]

[[tool.mypy.overrides]]
module = ["src.models", "src.models.gems_system_yml_schema", "src.models.modeler_parameter_yml_schema"]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["tests.e2e.end_2_end_tests", "tests.local_benchmark.benchmark"]
disable_error_code = ["operator"]

[[tool.mypy.overrides]]
module = ["pypsa.*", "pandas.*", "pydantic.*", "pytest.*", "gems.*"]
ignore_missing_imports = true
