* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 77
*   Variables        : 33
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 33
NAME          
ROWS
 N  COST
 G  generator_gen1.min_dispatch_0
 G  generator_gen1.min_dispatch_1
 G  generator_gen1.min_dispatch_2
 G  generator_gen1.min_dispatch_3
 G  generator_gen1.min_dispatch_4
 G  generator_gen1.min_dispatch_5
 G  generator_gen1.min_dispatch_6
 G  generator_gen1.min_dispatch_7
 G  generator_gen1.min_dispatch_8
 G  generator_gen1.min_dispatch_9
 L  generator_gen1.max_dispatch_0
 L  generator_gen1.max_dispatch_1
 L  generator_gen1.max_dispatch_2
 L  generator_gen1.max_dispatch_3
 L  generator_gen1.max_dispatch_4
 L  generator_gen1.max_dispatch_5
 L  generator_gen1.max_dispatch_6
 L  generator_gen1.max_dispatch_7
 L  generator_gen1.max_dispatch_8
 L  generator_gen1.max_dispatch_9
 G  generator_gen1.min_production
 L  generator_gen1.max_production
 G  generator_gen2.min_dispatch_0
 G  generator_gen2.min_dispatch_1
 G  generator_gen2.min_dispatch_2
 G  generator_gen2.min_dispatch_3
 G  generator_gen2.min_dispatch_4
 G  generator_gen2.min_dispatch_5
 G  generator_gen2.min_dispatch_6
 G  generator_gen2.min_dispatch_7
 G  generator_gen2.min_dispatch_8
 G  generator_gen2.min_dispatch_9
 L  generator_gen2.max_dispatch_0
 L  generator_gen2.max_dispatch_1
 L  generator_gen2.max_dispatch_2
 L  generator_gen2.max_dispatch_3
 L  generator_gen2.max_dispatch_4
 L  generator_gen2.max_dispatch_5
 L  generator_gen2.max_dispatch_6
 L  generator_gen2.max_dispatch_7
 L  generator_gen2.max_dispatch_8
 L  generator_gen2.max_dispatch_9
 G  generator_gen2.min_production
 L  generator_gen2.max_production
 G  generator_gen3.min_dispatch_0
 G  generator_gen3.min_dispatch_1
 G  generator_gen3.min_dispatch_2
 G  generator_gen3.min_dispatch_3
 G  generator_gen3.min_dispatch_4
 G  generator_gen3.min_dispatch_5
 G  generator_gen3.min_dispatch_6
 G  generator_gen3.min_dispatch_7
 G  generator_gen3.min_dispatch_8
 G  generator_gen3.min_dispatch_9
 L  generator_gen3.max_dispatch_0
 L  generator_gen3.max_dispatch_1
 L  generator_gen3.max_dispatch_2
 L  generator_gen3.max_dispatch_3
 L  generator_gen3.max_dispatch_4
 L  generator_gen3.max_dispatch_5
 L  generator_gen3.max_dispatch_6
 L  generator_gen3.max_dispatch_7
 L  generator_gen3.max_dispatch_8
 L  generator_gen3.max_dispatch_9
 G  generator_gen3.min_production
 L  generator_gen3.max_production
 E  bus_1.p_balance_0
 E  bus_1.p_balance_1
 E  bus_1.p_balance_2
 E  bus_1.p_balance_3
 E  bus_1.p_balance_4
 E  bus_1.p_balance_5
 E  bus_1.p_balance_6
 E  bus_1.p_balance_7
 E  bus_1.p_balance_8
 E  bus_1.p_balance_9
 E  bus_1.q_balance
COLUMNS
    generator_gen1.p_nom           generator_gen1.max_dispatch_0    -0.9  generator_gen1.max_dispatch_1   -0.91
    generator_gen1.p_nom           generator_gen1.max_dispatch_2   -0.92  generator_gen1.max_dispatch_3   -0.93
    generator_gen1.p_nom           generator_gen1.max_dispatch_4   -0.94  generator_gen1.max_dispatch_5   -0.95
    generator_gen1.p_nom           generator_gen1.max_dispatch_6   -0.96  generator_gen1.max_dispatch_7   -0.97
    generator_gen1.p_nom           generator_gen1.max_dispatch_8   -0.98  generator_gen1.max_dispatch_9   -0.99
    generator_gen1.p_s0_t0         COST                               50  generator_gen1.min_dispatch_0       1
    generator_gen1.p_s0_t0         generator_gen1.max_dispatch_0       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t0         generator_gen1.max_production       1  bus_1.p_balance_0                   1
    generator_gen1.p_s0_t1         COST                               50  generator_gen1.min_dispatch_1       1
    generator_gen1.p_s0_t1         generator_gen1.max_dispatch_1       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t1         generator_gen1.max_production       1  bus_1.p_balance_1                   1
    generator_gen1.p_s0_t2         COST                               50  generator_gen1.min_dispatch_2       1
    generator_gen1.p_s0_t2         generator_gen1.max_dispatch_2       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t2         generator_gen1.max_production       1  bus_1.p_balance_2                   1
    generator_gen1.p_s0_t3         COST                               50  generator_gen1.min_dispatch_3       1
    generator_gen1.p_s0_t3         generator_gen1.max_dispatch_3       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t3         generator_gen1.max_production       1  bus_1.p_balance_3                   1
    generator_gen1.p_s0_t4         COST                               50  generator_gen1.min_dispatch_4       1
    generator_gen1.p_s0_t4         generator_gen1.max_dispatch_4       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t4         generator_gen1.max_production       1  bus_1.p_balance_4                   1
    generator_gen1.p_s0_t5         COST                               50  generator_gen1.min_dispatch_5       1
    generator_gen1.p_s0_t5         generator_gen1.max_dispatch_5       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t5         generator_gen1.max_production       1  bus_1.p_balance_5                   1
    generator_gen1.p_s0_t6         COST                               50  generator_gen1.min_dispatch_6       1
    generator_gen1.p_s0_t6         generator_gen1.max_dispatch_6       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t6         generator_gen1.max_production       1  bus_1.p_balance_6                   1
    generator_gen1.p_s0_t7         COST                               50  generator_gen1.min_dispatch_7       1
    generator_gen1.p_s0_t7         generator_gen1.max_dispatch_7       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t7         generator_gen1.max_production       1  bus_1.p_balance_7                   1
    generator_gen1.p_s0_t8         COST                               50  generator_gen1.min_dispatch_8       1
    generator_gen1.p_s0_t8         generator_gen1.max_dispatch_8       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t8         generator_gen1.max_production       1  bus_1.p_balance_8                   1
    generator_gen1.p_s0_t9         COST                               50  generator_gen1.min_dispatch_9       1
    generator_gen1.p_s0_t9         generator_gen1.max_dispatch_9       1  generator_gen1.min_production       1
    generator_gen1.p_s0_t9         generator_gen1.max_production       1  bus_1.p_balance_9                   1
    generator_gen2.p_nom           generator_gen2.max_dispatch_0    -0.7  generator_gen2.max_dispatch_1   -0.71
    generator_gen2.p_nom           generator_gen2.max_dispatch_2   -0.72  generator_gen2.max_dispatch_3   -0.73
    generator_gen2.p_nom           generator_gen2.max_dispatch_4   -0.74  generator_gen2.max_dispatch_5   -0.75
    generator_gen2.p_nom           generator_gen2.max_dispatch_6   -0.76  generator_gen2.max_dispatch_7   -0.77
    generator_gen2.p_nom           generator_gen2.max_dispatch_8   -0.78  generator_gen2.max_dispatch_9   -0.79
    generator_gen2.p_s0_t0         COST                               10  generator_gen2.min_dispatch_0       1
    generator_gen2.p_s0_t0         generator_gen2.max_dispatch_0       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t0         generator_gen2.max_production       1  bus_1.p_balance_0                   1
    generator_gen2.p_s0_t1         COST                               10  generator_gen2.min_dispatch_1       1
    generator_gen2.p_s0_t1         generator_gen2.max_dispatch_1       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t1         generator_gen2.max_production       1  bus_1.p_balance_1                   1
    generator_gen2.p_s0_t2         COST                               10  generator_gen2.min_dispatch_2       1
    generator_gen2.p_s0_t2         generator_gen2.max_dispatch_2       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t2         generator_gen2.max_production       1  bus_1.p_balance_2                   1
    generator_gen2.p_s0_t3         COST                               10  generator_gen2.min_dispatch_3       1
    generator_gen2.p_s0_t3         generator_gen2.max_dispatch_3       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t3         generator_gen2.max_production       1  bus_1.p_balance_3                   1
    generator_gen2.p_s0_t4         COST                               10  generator_gen2.min_dispatch_4       1
    generator_gen2.p_s0_t4         generator_gen2.max_dispatch_4       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t4         generator_gen2.max_production       1  bus_1.p_balance_4                   1
    generator_gen2.p_s0_t5         COST                               10  generator_gen2.min_dispatch_5       1
    generator_gen2.p_s0_t5         generator_gen2.max_dispatch_5       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t5         generator_gen2.max_production       1  bus_1.p_balance_5                   1
    generator_gen2.p_s0_t6         COST                               10  generator_gen2.min_dispatch_6       1
    generator_gen2.p_s0_t6         generator_gen2.max_dispatch_6       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t6         generator_gen2.max_production       1  bus_1.p_balance_6                   1
    generator_gen2.p_s0_t7         COST                               10  generator_gen2.min_dispatch_7       1
    generator_gen2.p_s0_t7         generator_gen2.max_dispatch_7       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t7         generator_gen2.max_production       1  bus_1.p_balance_7                   1
    generator_gen2.p_s0_t8         COST                               10  generator_gen2.min_dispatch_8       1
    generator_gen2.p_s0_t8         generator_gen2.max_dispatch_8       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t8         generator_gen2.max_production       1  bus_1.p_balance_8                   1
    generator_gen2.p_s0_t9         COST                               10  generator_gen2.min_dispatch_9       1
    generator_gen2.p_s0_t9         generator_gen2.max_dispatch_9       1  generator_gen2.min_production       1
    generator_gen2.p_s0_t9         generator_gen2.max_production       1  bus_1.p_balance_9                   1
    generator_gen3.p_nom           generator_gen3.max_dispatch_0   -0.18  generator_gen3.max_dispatch_1   -0.18
    generator_gen3.p_nom           generator_gen3.max_dispatch_2   -0.18  generator_gen3.max_dispatch_3   -0.18
    generator_gen3.p_nom           generator_gen3.max_dispatch_4   -0.18  generator_gen3.max_dispatch_5   -0.18
    generator_gen3.p_nom           generator_gen3.max_dispatch_6   -0.18  generator_gen3.max_dispatch_7   -0.18
    generator_gen3.p_nom           generator_gen3.max_dispatch_8   -0.18  generator_gen3.max_dispatch_9   -0.18
    generator_gen3.p_s0_t0         COST                               10  generator_gen3.min_dispatch_0       1
    generator_gen3.p_s0_t0         generator_gen3.max_dispatch_0       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t0         generator_gen3.max_production       1  bus_1.p_balance_0                   1
    generator_gen3.p_s0_t1         COST                               10  generator_gen3.min_dispatch_1       1
    generator_gen3.p_s0_t1         generator_gen3.max_dispatch_1       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t1         generator_gen3.max_production       1  bus_1.p_balance_1                   1
    generator_gen3.p_s0_t2         COST                               10  generator_gen3.min_dispatch_2       1
    generator_gen3.p_s0_t2         generator_gen3.max_dispatch_2       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t2         generator_gen3.max_production       1  bus_1.p_balance_2                   1
    generator_gen3.p_s0_t3         COST                               10  generator_gen3.min_dispatch_3       1
    generator_gen3.p_s0_t3         generator_gen3.max_dispatch_3       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t3         generator_gen3.max_production       1  bus_1.p_balance_3                   1
    generator_gen3.p_s0_t4         COST                               10  generator_gen3.min_dispatch_4       1
    generator_gen3.p_s0_t4         generator_gen3.max_dispatch_4       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t4         generator_gen3.max_production       1  bus_1.p_balance_4                   1
    generator_gen3.p_s0_t5         COST                               10  generator_gen3.min_dispatch_5       1
    generator_gen3.p_s0_t5         generator_gen3.max_dispatch_5       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t5         generator_gen3.max_production       1  bus_1.p_balance_5                   1
    generator_gen3.p_s0_t6         COST                               10  generator_gen3.min_dispatch_6       1
    generator_gen3.p_s0_t6         generator_gen3.max_dispatch_6       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t6         generator_gen3.max_production       1  bus_1.p_balance_6                   1
    generator_gen3.p_s0_t7         COST                               10  generator_gen3.min_dispatch_7       1
    generator_gen3.p_s0_t7         generator_gen3.max_dispatch_7       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t7         generator_gen3.max_production       1  bus_1.p_balance_7                   1
    generator_gen3.p_s0_t8         COST                               10  generator_gen3.min_dispatch_8       1
    generator_gen3.p_s0_t8         generator_gen3.max_dispatch_8       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t8         generator_gen3.max_production       1  bus_1.p_balance_8                   1
    generator_gen3.p_s0_t9         COST                               10  generator_gen3.min_dispatch_9       1
    generator_gen3.p_s0_t9         generator_gen3.max_dispatch_9       1  generator_gen3.min_production       1
    generator_gen3.p_s0_t9         generator_gen3.max_production       1  bus_1.p_balance_9                   1
RHS
    RHS                            generator_gen1.min_dispatch_0      -0  generator_gen1.min_dispatch_1      -0
    RHS                            generator_gen1.min_dispatch_2      -0  generator_gen1.min_dispatch_3      -0
    RHS                            generator_gen1.min_dispatch_4      -0  generator_gen1.min_dispatch_5      -0
    RHS                            generator_gen1.min_dispatch_6      -0  generator_gen1.min_dispatch_7      -0
    RHS                            generator_gen1.min_dispatch_8      -0  generator_gen1.min_dispatch_9      -0
    RHS                            generator_gen1.max_dispatch_0      -0  generator_gen1.max_dispatch_1      -0
    RHS                            generator_gen1.max_dispatch_2      -0  generator_gen1.max_dispatch_3      -0
    RHS                            generator_gen1.max_dispatch_4      -0  generator_gen1.max_dispatch_5      -0
    RHS                            generator_gen1.max_dispatch_6      -0  generator_gen1.max_dispatch_7      -0
    RHS                            generator_gen1.max_dispatch_8      -0  generator_gen1.max_dispatch_9      -0
    RHS                            generator_gen1.min_production  -1e+20  generator_gen1.max_production   1e+20
    RHS                            generator_gen2.min_dispatch_0      -0  generator_gen2.min_dispatch_1      -0
    RHS                            generator_gen2.min_dispatch_2      -0  generator_gen2.min_dispatch_3      -0
    RHS                            generator_gen2.min_dispatch_4      -0  generator_gen2.min_dispatch_5      -0
    RHS                            generator_gen2.min_dispatch_6      -0  generator_gen2.min_dispatch_7      -0
    RHS                            generator_gen2.min_dispatch_8      -0  generator_gen2.min_dispatch_9      -0
    RHS                            generator_gen2.max_dispatch_0      -0  generator_gen2.max_dispatch_1      -0
    RHS                            generator_gen2.max_dispatch_2      -0  generator_gen2.max_dispatch_3      -0
    RHS                            generator_gen2.max_dispatch_4      -0  generator_gen2.max_dispatch_5      -0
    RHS                            generator_gen2.max_dispatch_6      -0  generator_gen2.max_dispatch_7      -0
    RHS                            generator_gen2.max_dispatch_8      -0  generator_gen2.max_dispatch_9      -0
    RHS                            generator_gen2.min_production  -1e+20  generator_gen2.max_production   1e+20
    RHS                            generator_gen3.min_dispatch_0      -0  generator_gen3.min_dispatch_1      -0
    RHS                            generator_gen3.min_dispatch_2      -0  generator_gen3.min_dispatch_3      -0
    RHS                            generator_gen3.min_dispatch_4      -0  generator_gen3.min_dispatch_5      -0
    RHS                            generator_gen3.min_dispatch_6      -0  generator_gen3.min_dispatch_7      -0
    RHS                            generator_gen3.min_dispatch_8      -0  generator_gen3.min_dispatch_9      -0
    RHS                            generator_gen3.max_dispatch_0      -0  generator_gen3.max_dispatch_1      -0
    RHS                            generator_gen3.max_dispatch_2      -0  generator_gen3.max_dispatch_3      -0
    RHS                            generator_gen3.max_dispatch_4      -0  generator_gen3.max_dispatch_5      -0
    RHS                            generator_gen3.max_dispatch_6      -0  generator_gen3.max_dispatch_7      -0
    RHS                            generator_gen3.max_dispatch_8      -0  generator_gen3.max_dispatch_9      -0
    RHS                            generator_gen3.min_production  -1e+20  generator_gen3.max_production   1e+20
    RHS                            bus_1.p_balance_0                 200  bus_1.p_balance_1                 210
    RHS                            bus_1.p_balance_2                 220  bus_1.p_balance_3                 230
    RHS                            bus_1.p_balance_4                 240  bus_1.p_balance_5                 250
    RHS                            bus_1.p_balance_6                 260  bus_1.p_balance_7                 270
    RHS                            bus_1.p_balance_8                 280  bus_1.p_balance_9                 290
    RHS                            bus_1.q_balance                    -0
BOUNDS
 FX BOUND                          generator_gen1.p_nom              200
 FR BOUND                          generator_gen1.p_s0_t0
 FR BOUND                          generator_gen1.p_s0_t1
 FR BOUND                          generator_gen1.p_s0_t2
 FR BOUND                          generator_gen1.p_s0_t3
 FR BOUND                          generator_gen1.p_s0_t4
 FR BOUND                          generator_gen1.p_s0_t5
 FR BOUND                          generator_gen1.p_s0_t6
 FR BOUND                          generator_gen1.p_s0_t7
 FR BOUND                          generator_gen1.p_s0_t8
 FR BOUND                          generator_gen1.p_s0_t9
 FX BOUND                          generator_gen2.p_nom              100
 FR BOUND                          generator_gen2.p_s0_t0
 FR BOUND                          generator_gen2.p_s0_t1
 FR BOUND                          generator_gen2.p_s0_t2
 FR BOUND                          generator_gen2.p_s0_t3
 FR BOUND                          generator_gen2.p_s0_t4
 FR BOUND                          generator_gen2.p_s0_t5
 FR BOUND                          generator_gen2.p_s0_t6
 FR BOUND                          generator_gen2.p_s0_t7
 FR BOUND                          generator_gen2.p_s0_t8
 FR BOUND                          generator_gen2.p_s0_t9
 FX BOUND                          generator_gen3.p_nom              100
 FR BOUND                          generator_gen3.p_s0_t0
 FR BOUND                          generator_gen3.p_s0_t1
 FR BOUND                          generator_gen3.p_s0_t2
 FR BOUND                          generator_gen3.p_s0_t3
 FR BOUND                          generator_gen3.p_s0_t4
 FR BOUND                          generator_gen3.p_s0_t5
 FR BOUND                          generator_gen3.p_s0_t6
 FR BOUND                          generator_gen3.p_s0_t7
 FR BOUND                          generator_gen3.p_s0_t8
 FR BOUND                          generator_gen3.p_s0_t9
ENDATA
