* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 0
*   Variables        : 3
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 3
NAME          
ROWS
 N  COST
BOUNDS
 FX BOUND                 generator_gen1.p_nom     200
 FX BOUND                 generator_gen2.p_nom     100
 FX BOUND                 generator_gen3.p_nom     100
ENDATA
